apiVersion: v1
kind: Secret
metadata:
  name: cognitive-apis
  namespace: crowd-analytics
data:
  APPINSIGHTS_INSTRUMENTATIONKEY: #{appInsightsKey}#
  serviceBusConnection: #{serviceBusConnection}#
  camFrameStorageConnection: #{camFrameStorageConnection}#
  cognitiveKey: #{cognitiveKey}#
  cognitiveEndpoint: #{cognitiveEndpoint}#
  cosmosDbEndpoint: #{cosmosDbEndpoint}#
  cosmosDbKey: #{cosmosDbKey}#
  faceWorkspaceDataFilter: #{faceWorkspaceDataFilter}#