apiVersion: v1
kind: Secret
metadata:
  name: crowd-analyzer
  namespace: crowd-analytics
data:
  AzureWebJobsStorage: #{funcStorage}#
  FUNCTIONS_WORKER_RUNTIME: #{funcRuntime}#
  APPINSIGHTS_INSTRUMENTATIONKEY: #{appInsightsKey}#
  serviceBusConnection: #{serviceBusConnection}#
  KEDA_SERVICE_BUS_CONNECTION: #{kedaServiceBusConnection}#
  origin: #{origin}#
  checkForDbConsistency: #{checkForDbConsistency}#
  cosmosDbEndpoint: #{cosmosDbEndpoint}#
  cosmosDbKey: #{cosmosDbKey}#
  faceWorkspaceDataFilter: #{faceWorkspaceDataFilter}#
  demographicsWindowMins: #{demographicsWindowMins}#